### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by tiexuedanxin** [leilimaster/DmifNet#4]
hello, I follow your reademe to train but the following error occured. There is no vaild_value.txt. Besides there also have many path problem such as '/home/lab105/lilei/occupancy_networks-master_batchhead/vaild_value.txt', Could you modified it with relative path.

[Errno 2] No such file or directory: '/home/lab105/lilei/occupancy_networks-master_batchhead/vaild_value.txt'
Traceback (most recent call last):
  File "train.py", line 185, in <module>
    % (model_selection_metric, metric_val))
NameError: name 'metric_val' is not defined

**Comment by Ray-tju** [comment]
> hello, I follow your reademe to train but the following error occured. There is no vaild_value.txt. Besides there also have many path problem such as '/home/lab105/lilei/occupancy_networks-master_batchhead/vaild_value.txt', Could you modified it with relative path.
> 
> [Errno 2] No such file or directory: '/home/lab105/lilei/occupancy_networks-master_batchhead/vaild_value.txt'
> Traceback (most recent call last):
> File "train.py", line 185, in
> % (model_selection_metric, metric_val))
> NameError: name 'metric_val' is not defined

Thanks, I fixed the bug.

**Comment by Ray-tju** [comment]
Thanks for your questions!
